<#
create_ca.ps1 - Create a test PQC CA and example node certificates using pqm4-compatible keys.
This is a PowerShell template. Replace placeholders with pqm4 tooling or wrappers.
#>
param(
    [string]$OutDir = "./test-ca"
)

New-Item -ItemType Directory -Path $OutDir -Force | Out-Null

Write-Host "Creating test CA in $OutDir"

$caKey = Join-Path $OutDir "ca_key.dil"
$caPub = Join-Path $OutDir "ca_pub.dil"
$caCert = Join-Path $OutDir "ca_cert.pem"

"CA_PRIVATE_KEY_PLACEHOLDER" | Out-File -FilePath $caKey -Encoding ascii
"CA_PUBLIC_KEY_PLACEHOLDER" | Out-File -FilePath $caPub -Encoding ascii
@"
-----BEGIN CERTIFICATE-----
MIID...PLACEHOLDER...IDAQAB
-----END CERTIFICATE-----
"@ | Out-File -FilePath $caCert -Encoding ascii

$readme = Join-Path $OutDir "README.txt"
@"
This directory contains a test CA created by scripts/ca/create_ca.ps1 (template).
Replace placeholder keys with actual Dilithium keys generated by pqm4 or your chosen tooling.
Files:
 - ca_key.dil      : CA private key (placeholder)
 - ca_pub.dil      : CA public key (placeholder)
 - ca_cert.pem     : CA cert in PEM-like placeholder format

Use scripts/ca/issue_node_cert.ps1 to issue node certificates signed by this CA (template).
"@ | Out-File -FilePath $readme -Encoding ascii

Write-Host "Created template CA at $OutDir"